### ISSUE TITLE
upgrade to Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by KrisThielemans** [CCPPETMR/CCPPETMR_VM#94]
It makes sense to upgrade from 16.04 LTS. Gadgetron is/will be using this as reference and needs more recent boost etc.

**Comment by paskino** [comment]
https://github.com/CCPPETMR/SIRF-SuperBuild/issues/146

Initial trouble is that in Ubuntu 18.04 there's Gnome3.

**Comment by paskino** [comment]
Following [this](https://github.com/gadgetron/gadgetron/issues/608) issue I will try the newest gadgetron.

**Comment by paskino** [comment]
What about python version? Shall I upgrade to 3?

**Comment by KrisThielemans** [comment]
There might be consequences for spyder and jupyter. Would have to be checked.

**Comment by KrisThielemans** [comment]
Trying the new VM. I got a message "Machine will suspend soon due to inactivity". Not a major problem of ourse, but a bit strange to have a VM suspend. [This might help](https://askubuntu.com/questions/1014965/automatic-suspend-computer-will-suspend-very-soon-because-of-inactivity-ho)

**Comment by KrisThielemans** [comment]
Running one of the jupyter notebook. Error
```python
 import matplotlib.pyplot as plt
```
produces
```
ImportError: No module named functools_lru_cache
```
Some possibly related comments on this [here](https://github.com/matplotlib/matplotlib/issues/9344/) with a manual work-around at the bottom:
```sh
sudo cp /usr/lib/python2.7/dist-packages/backports/functools_lru_cache.py /usr/local/lib/python2.7/dist-packages/backports/
```
That makes the import go one step further, but exists at
```
/usr/lib/python2.7/dist-packages/matplotlib/__init__.py in <module>()
    121 # cbook must import matplotlib only within function
    122 # definitions, so it is safe to import from it here.
--> 123 from . import cbook
    124 from matplotlib.cbook import (
    125     _backports, mplDeprecation, dedent, get_label, sanitize_sequence)

ImportError: cannot import name cbook
```
The first [google result](https://stackoverflow.com/questions/44623376/importerror-cannot-import-name-cbook) talks about various conflicts with ipython etc.

Funnily enough, after the above `cp` I don't have the `cbook` problem on the command line with `python` nor `ipython`. Not sure what python we're running from jupyter notebooks. (It says `python2`).

How did jupyter get installed anyway? I don't see it in our scripts.

This looks a bit like a rabbithole...
This looks

**Comment by KrisThielemans** [comment]
>How did jupyter get installed anyway? I don't see it in our scripts.

Sorry. it's [in the vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/f1bd1defee2f817498236312472e84ac7a299fe6/vagrant/Vagrantfile#L161) of course.

**Comment by paskino** [comment]
BTW, shall we build for python 3 rather than python 2.7?

**Comment by KrisThielemans** [comment]
I think the problem might be that we're using `apt-get` to install `matplotlib`, but `pip install jupyter`. Probably better to use `pip` for all python packages.

I haven't been able to try if this works or not, as I can't get an internet connection on the VM. Possibly because my VN is 5.2.12 (too old?). Note that after `update_VGA.sh`, I have a failure to install some vbox service.

**Comment by KrisThielemans** [comment]
installed VB 5.2.18, reimported, still problem with the `vboxadd-service` and no network connection. oh well

**Comment by KrisThielemans** [comment]
By the way, the mouse also moves really slowly for me on this VM (it's much faster on other VMs). Most likely something wrong with the VGA.

**Comment by paskino** [comment]
currently `vagrant up` hangs waiting for user input with a scrambled output
```
default: Unpacking software-properties-common (0.96.24.32.7) over (0.96.24.32.4) ...
    default: Package configuration┌──────────────────┤ Configuring keyboard-configuration ├──────────────────┐│
 The layout of keyboards varies per country, with some countries having   ││
 multiple common layouts. Please select the country of origin for the││
 keyboard of this computer.││││
 Country of origin for the keyboard:││││
Dutch↑││Dzongkha▒││English (Australian)▮││English (Cameroon)▒││English (Ghana)▒││
English (Nigeria)▒││English (South Africa)▒││English (UK)▒││English (US)                                  ↓││││││<Ok><Cancel>│││
└──────────────────────────────────────────────────────────────────────────┘
packing sosreport (3.6-1ubuntu0.18.04.2) over (3.5-1ubuntu3.18.04.1) ...
    default: Preparing to unpack .../81-tmux_2.6-3ubuntu0.1_amd64.deb ...
    default: Unpacking tmux (2.6-3ubuntu0.1) over (2.6-3) ...
    default: Preparing to unpack .../82-cloud-initramfs-copymods_0.40ubuntu1.1_all.deb ...
    default: Unpacking cloud-initramfs-copymods (0.40ubuntu1.1) over (0.40ubuntu1) ...
    default: Preparing to unpack .../83-cloud-initramfs-dyn-netconf_0.40ubuntu1.1_all.deb ...
    default: Unpacking cloud-initramfs-dyn-netconf (0.40ubuntu1.1) over (0.40ubuntu1) ...
    default: Preparing to unpack .../84-libtirpc1_0.2.5-1.2ubuntu0.1_amd64.deb ...
    default: Unpacking libtirpc1:amd64 (0.2.5-1.2ubuntu0.1) over (0.2.5-1.2) ...
    default: Preparing to unpack .../85-open-vm-tools_2%3a10.3.0-0ubuntu1~18.04.3_amd64.deb ...
    default: Unpacking open-vm-tools (2:10.3.0-0ubuntu1~18.04.3) over (2:10.2.0-3ubuntu3) ...
    default: Preparing to unpack .../86-overlayroot_0.40ubuntu1.1_all.deb ...
    default: Unpacking overlayroot (0.40ubuntu1.1) over (0.40ubuntu1) ...
    default: Setting up libquadmath0:amd64 (8.2.0-1ubuntu2~18.04) ...
    default: Setting up python-apt-common (1.6.3) ...
    default: Setting up libgomp1:amd64 (8.2.0-1ubuntu2~18.04) ...
    default: Setting up libatomic1:amd64 (8.2.0-1ubuntu2~18.04) ...
    default: Setting up libpython3.6-stdlib:amd64 (3.6.7-1~18.04) ...
    default: Setting up libisc169:amd64 (1:9.11.3+dfsg-1ubuntu1.3) ...
    default: Setting up libapt-inst2.0:amd64 (1.6.8) ...
    default: Setting up libnss-systemd:amd64 (237-3ubuntu10.11) ...
    default: Setting up git-man (1:2.17.1-1ubuntu0.4) ...
    default: Setting up keyboard-configuration (1.178ubuntu2.7) ...
    default:
```
